Repository NilFoundation/nil, pull requests merged in 2025-03, with the labels that each got.

#297 Added support to interact with a mapping via playground
  explorer_frontend/src/features/contracts/init.ts
Labels: playground

#357 [wallet extension] implement basic wallet sdk
  niljs/src/version.ts
  nix/npmdeps.nix
  package-lock.json
  wallet-extension/.env
  wallet-extension/README.md
  wallet-extension/biome.json
  wallet-extension/package.json
  wallet-extension/popup.html
  wallet-extension/public/icons/delete.svg
  wallet-extension/public/icons/linked.svg
  wallet-extension/public/icons/website.svg
  wallet-extension/public/locales/en/translation.json
  wallet-extension/public/locales/ru/transalation.json
  wallet-extension/public/manifest.json
  wallet-extension/src/background/background.ts
  wallet-extension/src/background/connection.ts
  wallet-extension/src/background/constants.ts
  wallet-extension/src/background/messagePassing/messageTypes.ts
  wallet-extension/src/background/messagePassing/messageUtils.ts
  wallet-extension/src/background/popup.ts
  wallet-extension/src/background/storage/index.ts
  wallet-extension/src/background/storage/storage.ts
  wallet-extension/src/background/transaction.ts
  wallet-extension/src/contentScripts/WindowNilProxy.ts
  wallet-extension/src/contentScripts/WindowNilRequestTypes.ts
  wallet-extension/src/contentScripts/injected.ts
  wallet-extension/src/contentScripts/methodHandler/ExtensionMethodHandler.ts
  wallet-extension/src/contentScripts/methodHandler/methods.ts
  wallet-extension/src/contentScripts/nil.ts
  wallet-extension/src/contentScripts/types.ts
  wallet-extension/src/features/blockchain/smartAccount.ts
  wallet-extension/src/features/store/model/token.ts
  wallet-extension/src/features/utils/errors.ts
  wallet-extension/src/features/utils/token.ts
  wallet-extension/src/features/utils/transaction.ts
  wallet-extension/src/i18n.ts
  wallet-extension/src/pages/requests/Connect.tsx
  wallet-extension/src/pages/requests/SignSend.tsx
  wallet-extension/src/pages/requests/index.ts
  wallet-extension/src/pages/wallet/Connection.tsx
  wallet-extension/src/pages/wallet/ErrorPage.tsx
  wallet-extension/src/pages/wallet/Send.tsx
  wallet-extension/src/pages/wallet/Settings.tsx
  wallet-extension/src/pages/wallet/index.ts
  wallet-extension/src/router/Wallet.tsx
  wallet-extension/src/router/routes.ts
  wallet-extension/test/integration/smartAccount.test.ts
  wallet-extension/tutorials/errors.md
  wallet-extension/tutorials/get-started.md
  wallet-extension/tutorials/transaction-types.md
  wallet-extension/vite.contentScript-injected.ts
  wallet-extension/vite.contentScript-nil.ts
Labels: wallet extension

#468 add copy of mock and custom tokens
  wallet-extension/src/features/components/wallet/home/TokenTab.tsx
  wallet-extension/src/features/utils/index.ts
  wallet-extension/src/features/utils/token.ts
Labels: wallet extension

#487 fix: wrap injected script in IIFE to prevent global variable leaks
  wallet-extension/vite.contentScript-nil.ts
Labels: wallet extension

#494 fix: support to pure type function and boolean inputs
  explorer_frontend/src/features/contracts/components/Management/Method.tsx
  explorer_frontend/src/features/contracts/init.ts
Labels: playground

#503 fix custom token in playground wallet
  explorer_frontend/src/features/account-connector/components/Token.tsx
  explorer_frontend/src/features/tokens/assets/custom.svg
  explorer_frontend/src/features/tokens/utils.ts
Labels: playground

#508 [cometa] fix compilation bug caused by missing generated files
  nil/services/cometa/compilation.go
  nil/services/cometa/service_test.go
  nil/services/cometa/tests/Issue465.sol
  nil/services/cometa/tests/issue465.json
Labels: cometa

#472 [explorer] implemented verification for interactive tutorials
  explorer_frontend/src/features/code/Code.tsx
  explorer_frontend/src/features/code/code-toolbar/CodeToolbar.tsx
  explorer_frontend/src/features/code/model.ts
  explorer_frontend/src/features/contracts/init.ts
  explorer_frontend/src/features/contracts/models/shardsAmount.ts
  explorer_frontend/src/features/logs/init.tsx
  explorer_frontend/src/features/shared/components/Link.tsx
  explorer_frontend/src/features/tutorial-check/checks/tutorialOneCheck.ts
  explorer_frontend/src/features/tutorial-check/init.ts
  explorer_frontend/src/features/tutorial-check/model.ts
  explorer_frontend/src/features/tutorial-check/spec.ts
  explorer_frontend/src/features/tutorial/TutorialText.tsx
  explorer_frontend/src/features/tutorial/assets/testContracts.sol
  explorer_frontend/src/features/tutorial/assets/testTutorial.md
  explorer_frontend/src/features/tutorial/assets/tutorialOneContracts.sol
  explorer_frontend/src/features/tutorial/assets/tutorialOneText.md
  explorer_frontend/src/features/tutorial/spec.ts
  explorer_frontend/src/init.ts
  explorer_frontend/src/pages/playground/PlaygroundPage.tsx
  explorer_frontend/src/pages/tutorials/TutorialMobileLayout.tsx
  explorer_frontend/src/pages/tutorials/TutorialPage.tsx
  explorer_frontend/src/pages/tutorials/init.ts
  explorer_frontend/src/pages/tutorials/model.tsx
Labels: explorer

#539 [playground] fix compile hotkey combo adds extra symbol to the code
  explorer_frontend/src/features/code/Code.tsx
  explorer_frontend/src/features/code/hooks/useCompileButton.tsx
Labels: playground

#430 Add call args playground validation and fix multiple token inputs issue
  explorer_frontend/src/features/account-connector/components/RpcUrlScreen.tsx
  explorer_frontend/src/features/account-connector/init.ts
  explorer_frontend/src/features/code/init.ts
  explorer_frontend/src/features/code/model.ts
  explorer_frontend/src/features/code/types.ts
  explorer_frontend/src/features/contracts/components/Contracts/Contract.tsx
  explorer_frontend/src/features/contracts/components/Management/Method.tsx
  explorer_frontend/src/features/contracts/components/Management/MethodInput.tsx
  explorer_frontend/src/features/contracts/components/Management/RemoveTokenButton.tsx
  explorer_frontend/src/features/contracts/init.ts
  explorer_frontend/src/features/contracts/models/base.ts
  explorer_frontend/src/features/contracts/models/callParamsValidation.ts
  explorer_frontend/src/features/contracts/models/exportApp.ts
  explorer_frontend/src/features/contracts/types.ts
  explorer_frontend/src/features/contracts/utils.tsx
  explorer_frontend/src/features/shared/utils/prepareFunctionValue.ts
Labels: playground

#572 [explorer] added link to tutorials from the index page of Explorer
  explorer_frontend/src/features/shared/components/Sidebar/Navigation.tsx
  explorer_frontend/src/features/tutorial-check/checks/tutorialTwoCheck.ts
Labels: explorer

#585 [explorer] added two more interactive tutorials
  explorer_frontend/src/features/contracts/models/base.ts
  explorer_frontend/src/features/tutorial-check/checks/tutorialFiveCheck.ts
  explorer_frontend/src/features/tutorial-check/checks/tutorialFourCheck.ts
  explorer_frontend/src/features/tutorial-check/checks/tutorialOneCheck.ts
  explorer_frontend/src/features/tutorial-check/checks/tutorialThreeCheck.ts
  explorer_frontend/src/features/tutorial-check/checks/tutorialTwoCheck.ts
  explorer_frontend/src/features/tutorial-check/spec.ts
  explorer_frontend/src/features/tutorial/TutorialsPanel.tsx
  explorer_frontend/src/features/tutorial/assets/tutorialFive/tutorialFiveContracts.sol
  explorer_frontend/src/features/tutorial/assets/tutorialFive/tutorialFiveIcon.svg
  explorer_frontend/src/features/tutorial/assets/tutorialFive/tutorialFiveText.md
  explorer_frontend/src/features/tutorial/assets/tutorialFour/tutorialFourContracts.sol
  explorer_frontend/src/features/tutorial/assets/tutorialFour/tutorialFourIcon.svg
  explorer_frontend/src/features/tutorial/assets/tutorialFour/tutorialFourText.md
  explorer_frontend/src/features/tutorial/assets/tutorialThree/tutorialThreeContracts.sol
  explorer_frontend/src/features/tutorial/spec.ts
Labels: documentation

#591 [docs] added migration guide for new release
  docs/docusaurus.config.js
  docs/nil/migration-guides/march-1803-2025-release.mdx
  docs/sidebar-nil.js
Labels: documentation

#590 [explorer] adjusted imports for tutorials to avoid unnecessary awaits
  explorer_frontend/src/features/tutorial-check/checks/tutorialFiveCheck.ts
  explorer_frontend/src/features/tutorial/spec.ts
  explorer_frontend/src/features/tutorial/tutorialImports.ts
  explorer_frontend/vite.config.ts
Labels: playground, explorer

#604 [playground] fixed second tutorial
  explorer_frontend/src/features/tutorial-check/checks/tutorialTwoCheck.ts
  explorer_frontend/src/features/tutorial/assets/tutorialTwo/tutorialTwoContracts.sol
Labels: documentation, explorer

#615 [niljs] Fix niljs builds
  academy/lending-protocol/package-lock.json
  academy/lending-protocol/package.json
  clijs/package.json
  docs/package.json
  niljs/package.json
  nix/npmdeps.nix
  package-lock.json
  package.json
  rollup-bridge-contracts/package.json
  smart-contracts/package.json
  wallet-extension/package.json
Labels: niljs

#571 [niljs] errors improvements
  niljs/package.json
  niljs/src/clients/PublicClient.ts
  niljs/src/docsBaseUrl.ts
  niljs/src/errors/BaseError.ts
  niljs/src/errors/block.ts
  niljs/src/errors/encoding.ts
  niljs/src/errors/shardId.ts
  niljs/test/testEnv.ts
Labels: niljs

#633 [docs] fix docs_ai_back build by adjusting typescript config
  docs_ai_backend/tsconfig.json
Labels: documentation

#678 Review/update txn UI
  explorer_frontend/src/features/transaction/components/Logs.tsx
  explorer_frontend/src/features/transaction/components/Transaction.tsx
  explorer_frontend/src/features/transaction/components/assets/no-log.svg
  explorer_frontend/src/pages/transaction/TransactionPage.tsx
Labels: ODHack12

#687 Review/feat:improve sql chronological tx sort
  explorer_backend/daos/transactions.ts
Labels: ODHack12

#710 [misc] corrected licence files in READMEs
  create-nil-hardhat-project/README.MD
  docs/README.md
  smart-contracts/README.md
Labels: documentation

#712 [playground] remove rpcUrl validation
  explorer_frontend/biome.json
  explorer_frontend/src/features/account-connector/components/RpcUrlScreen.tsx
  explorer_frontend/src/features/account-connector/init.ts
  explorer_frontend/src/features/account-connector/model.ts
  explorer_frontend/src/features/account-connector/validation.ts
Labels: playground
