Repository NilFoundation/nil, pull requests merged in 2025-04, with the labels that each got.

#664 [ACADEMY] Sharded Voting Example
  .gitignore
  academy/README.md
  academy/lending-protocol/package-lock.json
  academy/sharded-voting-protocol/.env.example
  academy/sharded-voting-protocol/.gitignore
  academy/sharded-voting-protocol/README.md
  academy/sharded-voting-protocol/biome.json
  academy/sharded-voting-protocol/contracts/VoteManager.sol
  academy/sharded-voting-protocol/contracts/VoteShard.sol
  academy/sharded-voting-protocol/hardhat.config.ts
  academy/sharded-voting-protocol/package-lock.json
  academy/sharded-voting-protocol/package.json
  academy/sharded-voting-protocol/task/run-voting-protocol.ts
  academy/sharded-voting-protocol/tsconfig.json
Labels: ODHack12

#709 [tutorial] added misc UX improvements
  explorer_frontend/src/features/tutorial-check/checks/tutorialFiveCheck.ts
  explorer_frontend/src/features/tutorial-check/checks/tutorialFourCheck.ts
  explorer_frontend/src/features/tutorial-check/checks/tutorialOneCheck.ts
  explorer_frontend/src/features/tutorial-check/checks/tutorialThreeCheck.ts
  explorer_frontend/src/features/tutorial-check/checks/tutorialTwoCheck.ts
  explorer_frontend/src/features/tutorial/assets/tutorialFive/tutorialFiveContracts.sol
  explorer_frontend/src/features/tutorial/assets/tutorialFive/tutorialFiveText.md
  explorer_frontend/src/features/tutorial/assets/tutorialFour/tutorialFourContracts.sol
  explorer_frontend/src/features/tutorial/assets/tutorialOne/tutorialOneContracts.sol
  explorer_frontend/src/features/tutorial/assets/tutorialThree/tutorialThreeContracts.sol
  explorer_frontend/src/features/tutorial/assets/tutorialThree/tutorialThreeText.md
  explorer_frontend/src/features/tutorial/assets/tutorialTwo/tutorialTwoContracts.sol
  explorer_frontend/src/features/tutorial/init.ts
  explorer_frontend/src/features/tutorial/model.ts
  explorer_frontend/src/features/tutorial/spec.ts
  nix/npmdeps.nix
  pnpm-lock.yaml
Labels: playground, explorer

#735 [explorer] add EXPLORER_CODE_SNIPPETS_DB_PATH env var to config
  explorer_backend/config.ts
  explorer_backend/services/sqlite.ts
  nix/container.nix
Labels: explorer

#661 feat: make transaction methods awaitable
  academy/lending-protocol/task/run-lending-protocol.ts
  clijs/src/commands/smart-account/deploy.ts
  clijs/src/commands/smart-account/new.ts
  clijs/src/commands/smart-account/send-tokens.ts
  clijs/src/commands/smart-account/send-transaction.ts
  create-nil-hardhat-project/src/deploy.ts
  create-nil-hardhat-project/test/Await.ts
  docs/nil/niljs/reading-writing-info.mdx
  docs/tests/clone-factory.test.mts
  docs/tests/cometa-and-debugging.test.mts
  docs/tests/cookbook-deploy-smart-contract.test.mts
  docs/tests/cookbook-english-auction.test.mts
  docs/tests/cookbook-multisig.test.mts
  docs/tests/cookbook-swap.test.mjs
  docs/tests/multi-tokens-support.test.mjs
  docs/tests/working-with-smart-contracts-niljs.test.mjs
  explorer_frontend/src/features/contracts/models/base.ts
  explorer_frontend/src/features/tutorial-check/checks/tutorialFiveCheck.ts
  explorer_frontend/src/features/tutorial-check/checks/tutorialFourCheck.ts
  explorer_frontend/src/features/tutorial-check/checks/tutorialOneCheck.ts
  explorer_frontend/src/features/tutorial-check/checks/tutorialThreeCheck.ts
  explorer_frontend/src/features/tutorial-check/checks/tutorialTwoCheck.ts
  niljs/README.md
  niljs/examples/asyncCall.ts
  niljs/examples/bounce.ts
  niljs/examples/deployInternalTransaction.ts
  niljs/examples/tokenMint.ts
  niljs/src/contract-factory/contractInteraction.ts
  niljs/src/index.ts
  niljs/src/smart-accounts/SmartAccountInterface.ts
  niljs/src/smart-accounts/SmartAccountV1/SmartAccountV1.test.ts
  niljs/src/smart-accounts/SmartAccountV1/SmartAccountV1.ts
  niljs/src/types/IReceipt.ts
  niljs/src/utils/receipt.ts
  niljs/src/utils/transaction.ts
  niljs/test/integration/bounce.test.ts
  niljs/test/integration/call.test.ts
  niljs/test/integration/calling.test.ts
  niljs/test/integration/deploy.test.ts
  niljs/test/integration/factory.test.ts
  niljs/test/integration/tokens.test.ts
  package.json
  uniswap/tasks/util/deploy.ts
  wallet-extension/src/features/blockchain/smartAccount.ts
Labels: ODHack12

#748 Add basic code for Parsing Bytecode
  explorer_frontend/src/features/transaction/components/Overview.tsx
Labels: ODHack12

#657 Feat/contract import
  academy/lending-protocol/task/run-lending-protocol.ts
  explorer_frontend/src/features/contracts/models/base.ts
  explorer_frontend/src/features/shared/utils/solidityCompiler/helper.ts
  explorer_frontend/src/features/shared/utils/solidityCompiler/index.ts
  explorer_frontend/src/features/shared/utils/solidityCompiler/processImports.ts
  explorer_frontend/tests/tutorials/tutorials.test.mts
Labels: ODHack12

#753 feat: implement token splitter contract
  academy/token-split/.env.example
  academy/token-split/.gitignore
  academy/token-split/biome.json
  academy/token-split/contracts/tokenSplitter.sol
  academy/token-split/hardhat.config.ts
  academy/token-split/package.json
  academy/token-split/task/deploy_and_test_tokensplitter.ts
  academy/token-split/tsconfig.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: ODHack12

#343 Add cometa niljs integration tests
  academy/token-split/task/deploy_and_test_tokensplitter.ts
  clijs/src/commands/smart-account/deploy.ts
  flake.nix
  niljs/package.json
  niljs/src/clients/CometaClient.ts
  niljs/src/clients/types/CometaTypes.ts
  niljs/src/encoding/toHex.ts
  niljs/src/utils/hex.ts
  niljs/test/integration/cometa.test.ts
  niljs/test/mocks/cometa-config.yml
  niljs/test/vitest.integration.config.ts
  nix/niljs.nix
Labels: niljs

#677 [playground] add Playground version to playground logo
  explorer_frontend/.env
  explorer_frontend/src/features/shared/components/Layout/Logo.tsx
  explorer_frontend/src/features/shared/components/Layout/Navbar.tsx
  explorer_frontend/src/features/shared/components/Layout/index.tsx
  explorer_frontend/src/features/shared/components/Layout/styles.ts
  explorer_frontend/src/features/shared/index.ts
  explorer_frontend/src/pages/playground/PlaygroundPage.tsx
  explorer_frontend/src/pages/tutorials/TutorialPage.tsx
  flake.nix
  nix/nilexplorer.nix
Labels: playground

#794 [playground] implemented the new UI for tutorials and the Playground
  explorer_frontend/src/features/account-connector/components/AccountPane.tsx
  explorer_frontend/src/features/account-connector/components/styles.ts
  explorer_frontend/src/features/code/Code.tsx
  explorer_frontend/src/features/code/assets/DocsIcon.tsx
  explorer_frontend/src/features/code/assets/GithubIcon.tsx
  explorer_frontend/src/features/code/assets/PlaygroundIcon.tsx
  explorer_frontend/src/features/code/assets/ResourcesIcon.tsx
  explorer_frontend/src/features/code/assets/SupportIcon.tsx
  explorer_frontend/src/features/code/assets/TelegramIcon.tsx
  explorer_frontend/src/features/code/assets/TutorialsIcon.tsx
  explorer_frontend/src/features/code/code-toolbar/CodeToolbar.tsx
  explorer_frontend/src/features/code/code-toolbar/CompileVersionButton.tsx
  explorer_frontend/src/features/code/code-toolbar/CompilerVersionButton.tsx
  explorer_frontend/src/features/code/code-toolbar/HyperlinkButton.tsx
  explorer_frontend/src/features/code/code-toolbar/OpenProjectButton.tsx
  explorer_frontend/src/features/code/code-toolbar/QuestionButton.tsx
  explorer_frontend/src/features/code/code-toolbar/ResourcesButton.tsx
  explorer_frontend/src/features/contracts/components/Contracts/Contracts.tsx
  explorer_frontend/src/features/contracts/components/ContractsContainer.tsx
  explorer_frontend/src/features/healthcheck/components/NetworkErrorNotification.tsx
  explorer_frontend/src/features/shared/components/InternalPageContainer.tsx
  explorer_frontend/src/features/shared/components/Layout/Logo.tsx
  explorer_frontend/src/features/shared/components/Layout/Navbar.tsx
  explorer_frontend/src/features/shared/components/Layout/styles.ts
  explorer_frontend/src/features/transaction-list/components/TransactionList.tsx
  explorer_frontend/src/pages/playground/PlaygroundPage.tsx
  explorer_frontend/src/pages/tutorials/TutorialMobileLayout.tsx
  explorer_frontend/src/pages/tutorials/TutorialPage.tsx
  explorer_frontend/src/pages/tutorials/init.ts
  explorer_frontend/src/styleHelpers.ts
  explorer_frontend/src/themes.tsx
Labels: playground

#766 [playground] : added support for inputting arrays and tuple result parsing
  explorer_frontend/src/features/contracts/components/Management/MethodInput.tsx
  explorer_frontend/src/features/contracts/init.ts
  explorer_frontend/src/features/contracts/utils.tsx
  explorer_frontend/src/features/logs/init.tsx
Labels: playground

#815 [niljs] remove nil from default nix package inputs
  flake.nix
Labels: niljs

#807 [docs] added a migration guide for the 16/04 release
  docs/docusaurus.config.js
  docs/nil/migration-guides/april-1604-2025-release.mdx
  docs/sidebar-nil.js
Labels: documentation

#824 [GH-#] dev.js/run.js fix
  clijs/src/commands/smart-account/call-readonly.ts
  clijs/src/commands/smart-account/deploy.ts
  clijs/src/commands/smart-account/estimate-fee.ts
  clijs/src/commands/smart-account/new.ts
  clijs/src/commands/smart-account/send-tokens.ts
  clijs/src/commands/smart-account/send-transaction.ts
  clijs/src/commands/smart-account/top-up.ts
Labels: CLI

#822 [explorer] add unit tests setup and AccountInfo test for explorer
  explorer_frontend/package.json
  explorer_frontend/src/features/account/components/AccountInfo.test.tsx
  explorer_frontend/src/features/account/components/AccountInfo.tsx
  explorer_frontend/tests/unit/TestsLayout.tsx
  explorer_frontend/tests/unit/renderWithLayout.ts
  explorer_frontend/tests/unit/setupUnitTests.ts
  explorer_frontend/tests/vitest.config.ts
  explorer_frontend/tsconfig.json
  explorer_frontend/typings.d.ts
  explorer_frontend/vite.config.ts
  nix/nilexplorer.nix
  nix/npmdeps.nix
  pnpm-lock.yaml
Labels: playground, explorer

#676 Feat: Applied new Explorer resizing logic
  explorer_frontend/src/features/search/components/Search.tsx
  explorer_frontend/src/features/shared/components/InternalPageContainer.tsx
  explorer_frontend/src/features/shared/components/Layout/Navbar.tsx
  explorer_frontend/src/features/shared/components/Layout/styles.ts
  explorer_frontend/src/features/shared/components/MobileConvertableTable.tsx
  explorer_frontend/src/features/transaction-list/components/TransactionList.tsx
  explorer_frontend/src/features/transaction/components/Logs.tsx
  explorer_frontend/src/pages/address/AddressPage.tsx
  explorer_frontend/src/pages/block/BlockPage.tsx
  explorer_frontend/src/pages/explorer/ExplorerPage.tsx
  explorer_frontend/src/pages/explorer/styles.ts
  explorer_frontend/src/pages/transaction/TransactionPage.tsx
  explorer_frontend/src/styleHelpers.ts
Labels: ODHack12

#762 fix: Block Explorer Page Update
  explorer_frontend/src/features/block/components/BlockInfo.tsx
  explorer_frontend/src/features/block/components/BlockNavigation.tsx
  explorer_frontend/src/features/shared/components/DangerIcon.tsx
  explorer_frontend/src/features/shared/components/EmptyList.tsx
  explorer_frontend/src/features/shared/components/InternalPageContainer.tsx
  explorer_frontend/src/features/shared/components/Layout/styles.ts
  explorer_frontend/src/features/shared/components/OverflowEllipsis/index.tsx
  explorer_frontend/src/features/shared/components/PaginationIcons.tsx
  explorer_frontend/src/features/shared/components/RightArrowIcon.tsx
  explorer_frontend/src/features/shared/index.ts
  explorer_frontend/src/features/transaction-list/components/EmptyTransactionList.tsx
  explorer_frontend/src/features/transaction-list/components/TransactionList.tsx
  explorer_frontend/src/features/transaction-list/components/TransactionsTable.tsx
  explorer_frontend/src/features/transaction-list/model.ts
  explorer_frontend/src/pages/block/BlockPage.tsx
Labels: ODHack12

#855 [clijs] add receipt command
  clijs/bin/dev.js
  clijs/bin/run.js
  clijs/src/base.ts
  clijs/src/commands/block.ts
  clijs/src/commands/receipt.ts
  clijs/src/common/config.test.ts
  clijs/src/sea.ts
  clijs/test/commands/receipt.test.ts
  clijs/test/setup.ts
  niljs/src/clients/BaseClient.ts
  niljs/src/utils/faucet.ts
Labels: CLI
