Repository NilFoundation/nil, pull requests merged in 2025-02, with the labels that each got.

#118 Rename getMessageReceiptByHash to getTransactionReceiptByHash
  explorer_frontend/src/features/contracts/models/base.ts
Labels: sandbox

#122 [docs] fixes to 500 links
  docs/nil/intro.mdx
Labels: documentation

#129 [docs] return of the switch
  docs/docusaurus.config.js
  docs/src/css/custom.css
Labels: documentation

#137 [docs] upgraded docusaurus to the latest version
  docs/docusaurus.config.js
  docs/package.json
  docs/plugins/custom-loader/index.js
  docs/plugins/custom-loader/package.json
  docs/src/theme/DocBreadcrumbs/Items/Home/index.tsx
  docs/src/theme/DocBreadcrumbs/Items/Home/styles.module.css
  docs/src/theme/DocBreadcrumbs/index.tsx
  docs/src/theme/DocBreadcrumbs/styles.module.css
  docs/src/theme/DocSidebarItem/Category/index.tsx
  docs/src/theme/DocSidebarItem/Html/index.tsx
  docs/src/theme/DocSidebarItem/Html/styles.module.css
  docs/src/theme/DocSidebarItem/Link/index.tsx
  docs/src/theme/DocSidebarItem/Link/styles.module.css
  docs/src/theme/DocSidebarItem/index.tsx
  docs/src/theme/NavbarItem/ComponentTypes.tsx
  docs/src/theme/NavbarItem/DefaultNavbarItem.tsx
  docs/src/theme/NavbarItem/DocNavbarItem.tsx
  docs/src/theme/NavbarItem/DocSidebarNavbarItem.tsx
  docs/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.tsx
  docs/src/theme/NavbarItem/DocsVersionNavbarItem.tsx
  docs/src/theme/NavbarItem/DropdownNavbarItem/index.tsx
  docs/src/theme/NavbarItem/DropdownNavbarItem/styles.module.css
  docs/src/theme/NavbarItem/HtmlNavbarItem.tsx
  docs/src/theme/NavbarItem/LocaleDropdownNavbarItem/index.tsx
  docs/src/theme/NavbarItem/LocaleDropdownNavbarItem/styles.module.css
  docs/src/theme/NavbarItem/NavbarNavLink.tsx
  docs/src/theme/NavbarItem/SearchNavbarItem.tsx
  docs/src/theme/NavbarItem/index.tsx
  nix/npmdeps.nix
  package-lock.json
Labels: documentation

#155 [docs] ai improvements to support streaming
  docs/src/components/CustomChatRuntimeProvider/index.tsx
  docs_ai_backend/app/api/chat/route.ts
Labels: documentation

#138 [docs] added explanation of the new fee model
  docs/nil/getting-started/gas-and-value.mdx
Labels: documentation

#133 Make cometa contract register optional
  explorer_frontend/src/features/contracts/init.ts
  explorer_frontend/src/features/contracts/models/base.ts
  explorer_frontend/src/features/logs/init.tsx
Labels: sandbox

#132 Don't save latest project if code is empty
  explorer_frontend/public/runtime-config.toml
  explorer_frontend/src/features/code/init.ts
  explorer_frontend/src/features/contracts/components/Deploy/ShardIdInput.tsx
  explorer_frontend/src/features/runtime-config/runtime-config.d.ts
Labels: playground

#198 [docs] adjusted prompts and added a timeout error
  docs/src/components/CustomChatRuntimeProvider/index.tsx
  docs_ai_backend/app/api/chat/route.ts
  docs_ai_backend/src/core/QueryHandler.ts
  nix/npmdeps.nix
  package-lock.json
Labels: documentation

#200 [docs] Update path to installed smart-contracts
  docs_ai_backend/src/utils/populateDB.js
Labels: documentation

#201 [docs] additional prompt refinement
  docs/src/components/CustomChatRuntimeProvider/index.tsx
  docs_ai_backend/app/api/chat/route.ts
  docs_ai_backend/src/core/QueryHandler.ts
Labels: documentation

#190 Remove rpc-types package and ts-code generator
  go.mod
  go.sum
  nil/cmd/ts_generate/main.go
  nil/services/rpc/ts.go
  nil/services/rpc/ts_test.go
  nix/nil.nix
  nix/npmdeps.nix
  package-lock.json
  rpc-types/.gitignore
  rpc-types/README.md
  rpc-types/package.json
  rpc-types/scripts/generate-types.js
  rpc-types/src/index.ts
  rpc-types/tsconfig.json
Labels: niljs

#180 Allow to pass custom headers to http-transport in niljs
  niljs/src/rpc/rpcClient.test.ts
  niljs/src/rpc/rpcClient.ts
  niljs/src/transport/HttpTransport.ts
  niljs/src/transport/types/IHttpTransportConfig.ts
  niljs/src/utils/rpc.ts
Labels: niljs

#232 Remove barrel files from niljs
  .vscode/settings.json
  niljs/biome.json
  niljs/src/clients/BaseClient.ts
  niljs/src/clients/CometaService.test.ts
  niljs/src/clients/FaucetClient.test.ts
  niljs/src/clients/FaucetClient.ts
  niljs/src/clients/PublicClient.test.ts
  niljs/src/clients/PublicClient.ts
  niljs/src/clients/constants.ts
  niljs/src/clients/index.ts
  niljs/src/clients/types/IDeployData.ts
  niljs/src/contract-factory/ContractFactory.ts
  niljs/src/contract-factory/contractInteraction.ts
  niljs/src/contract-factory/index.ts
  niljs/src/contracts/SmartAccountV1/index.ts
  niljs/src/contracts/index.ts
  niljs/src/encoding/externalTransaction.ts
  niljs/src/encoding/fromBytes.ts
  niljs/src/encoding/fromHex.ts
  niljs/src/encoding/index.ts
  niljs/src/errors/block.ts
  niljs/src/errors/index.ts
  niljs/src/index.ts
  niljs/src/signers/LocalECDSAKeySigner.test.ts
  niljs/src/signers/LocalECDSAKeySigner.ts
  niljs/src/signers/index.ts
  niljs/src/signers/mnemonic.test.ts
  niljs/src/signers/mnemonic.ts
  niljs/src/signers/publicKey.test.ts
  niljs/src/signers/types/ISignature.ts
  niljs/src/smart-accounts/SmartAccountV1/SmartAccountV1.test.ts
  niljs/src/smart-accounts/SmartAccountV1/SmartAccountV1.ts
  niljs/src/smart-accounts/SmartAccountV1/types.ts
  niljs/src/smart-accounts/index.ts
  niljs/src/transport/index.ts
  niljs/src/types/ISignedTransaction.ts
  niljs/src/types/index.ts
  niljs/src/utils/address.ts
  niljs/src/utils/assert.ts
  niljs/src/utils/block.ts
  niljs/src/utils/faucet.ts
  niljs/src/utils/hex.ts
  niljs/src/utils/index.ts
  niljs/src/utils/refiners.ts
  niljs/src/utils/smart-account.ts
Labels: niljs

#205 [docs] added docs interactive tutorials service
  .gitignore
  .vscode/settings.json
  docs_ai_backend/README.md
  docs_interactive_tutorials_service/README.md
  docs_interactive_tutorials_service/biome.json
  docs_interactive_tutorials_service/eslint.config.mjs
  docs_interactive_tutorials_service/next-env.d.ts
  docs_interactive_tutorials_service/next.config.ts
  docs_interactive_tutorials_service/package.json
  docs_interactive_tutorials_service/src/app/api/user/route.ts
  docs_interactive_tutorials_service/src/clients/DBClient.ts
  docs_interactive_tutorials_service/tsconfig.json
  flake.nix
  nix/docstutorialsservice.nix
  nix/npmdeps.nix
  package-lock.json
  package.json
Labels: documentation

#238 [docs] fixed CLI refs generation
  docs/nil/prerequisites.mdx
  docs/nil/scripts/cliRefGenerator.ts
  nix/nildocs.nix
Labels: documentation

#257 Rename 'sandbox' to 'playground'
  README.md
  docs/nil/guides/cometa-and-debugging.mdx
  docs/nil/intro.mdx
  docs/plugins/nil-playground-plugin/theme/PGButton.js
  explorer_frontend/public/runtime-config.toml
  explorer_frontend/src/features/account-connector/components/TopUpPanel.tsx
  explorer_frontend/src/features/account-connector/init.ts
  explorer_frontend/src/features/code/Code.tsx
  explorer_frontend/src/features/code/code-toolbar/HyperlinkButton.tsx
  explorer_frontend/src/features/code/code-toolbar/QuestionButton.tsx
  explorer_frontend/src/features/code/init.ts
  explorer_frontend/src/features/contracts/components/Contracts/Contracts.tsx
  explorer_frontend/src/features/logs/components/Logs.tsx
  explorer_frontend/src/features/logs/components/LogsGreeting.tsx
  explorer_frontend/src/features/routing/components/RoutesView.tsx
  explorer_frontend/src/features/routing/index.ts
  explorer_frontend/src/features/routing/routes/playgroundRoute.ts
  explorer_frontend/src/features/routing/routes/routes.ts
  explorer_frontend/src/features/routing/routes/sandboxRoute.ts
  explorer_frontend/src/features/runtime-config/runtime-config.d.ts
  explorer_frontend/src/features/sandbox/init.ts
  explorer_frontend/src/features/sandbox/models/model.ts
  explorer_frontend/src/features/shared/components/Sidebar/Navigation.tsx
  explorer_frontend/src/init.ts
  explorer_frontend/src/pages/playground/PlaygroundMobileLayout.tsx
  explorer_frontend/src/pages/playground/PlaygroundPage.tsx
  explorer_frontend/src/pages/playground/index.tsx
  explorer_frontend/src/pages/playground/init.ts
  explorer_frontend/src/pages/playground/model.ts
  explorer_frontend/src/pages/sandbox/index.tsx
  explorer_frontend/tests/e2e/sandbox.cy.ts
  wallet-extension/README.md
Labels: playground

#258 [docs] fix to ansible on nil-docs
  nix/npmdeps.nix
  package-lock.json
Labels: documentation

#273 Show warning in playground if sa is not connected
  explorer_frontend/src/features/contracts/assets/arrow-circle-up.svg
  explorer_frontend/src/features/contracts/components/Contracts/Contract.tsx
  explorer_frontend/src/features/contracts/components/Contracts/Contracts.tsx
  explorer_frontend/src/features/contracts/components/Contracts/SmartAccountNotConnectedWarning.tsx
Labels: playground

#290 Add shardid validation to deploy modal
  explorer_frontend/src/features/account-connector/init.ts
  explorer_frontend/src/features/code/init.ts
  explorer_frontend/src/features/code/model.ts
  explorer_frontend/src/features/contracts/components/Deploy/DeployTab.tsx
  explorer_frontend/src/features/contracts/components/Deploy/ShardIdInput.tsx
  explorer_frontend/src/features/contracts/init.ts
  explorer_frontend/src/features/contracts/models/base.ts
  explorer_frontend/src/features/shards/init.ts
  explorer_frontend/src/features/shards/models/model.ts
  explorer_frontend/src/pages/playground/PlaygroundPage.tsx
Labels: playground

#288 publish .env for wallet
  wallet-extension/.env
  wallet-extension/.gitignore
Labels: wallet extension

#295 fixed formatting of balances in contract management
  explorer_frontend/src/features/contracts/components/Management/ContractManagement.tsx
Labels: playground

#294 add integration tests in wallet extension
  flake.nix
  nix/npmdeps.nix
  nix/walletextension.nix
  package-lock.json
  wallet-extension/package.json
  wallet-extension/test/integration/faucet.test.ts
  wallet-extension/test/integration/helper.ts
  wallet-extension/test/integration/smartAccount.test.ts
  wallet-extension/test/testEnv.ts
  wallet-extension/test/vitest.integration.config.ts
  wallet-extension/tsconfig.app.json
Labels: wallet extension

#308 remove unused dep in wallet extension
  wallet-extension/package.json
Labels: wallet extension

#305 Add playground rpc api healthcheck
  explorer_frontend/src/features/account-connector/components/MainScreen.tsx
  explorer_frontend/src/features/contracts/components/Contracts/Contract.tsx
  explorer_frontend/src/features/contracts/components/Contracts/Contracts.tsx
  explorer_frontend/src/features/healthcheck/components/NetworkErrorNotification.tsx
  explorer_frontend/src/features/healthcheck/index.ts
  explorer_frontend/src/features/healthcheck/init.ts
  explorer_frontend/src/features/healthcheck/model.ts
  explorer_frontend/src/init.ts
  explorer_frontend/src/pages/playground/PlaygroundPage.tsx
Labels: playground

#277 Throw error if in playground import nonexistent smart contract
  explorer_frontend/src/features/contracts/components/Deploy/DeployContractModal.tsx
  explorer_frontend/src/features/contracts/components/Deploy/ImportContractTab.tsx
  explorer_frontend/src/features/contracts/init.ts
  explorer_frontend/src/features/contracts/models/base.ts
  explorer_frontend/src/features/logs/init.tsx
Labels: playground

#312 Set initial random shard-id in playground
  explorer_frontend/src/features/contracts/init.ts
  explorer_frontend/src/features/contracts/models/base.ts
Labels: playground

#330 [docs] card removal to avoid confusion
  docs/nil/intro.mdx
Labels: documentation

#328 [docs] typos fix by @samdotola
  README.md
  docs/nil/architecture/contract-co-location.mdx
  docs/nil/architecture/data-availability.mdx
  docs/nil/cookbook/english-auction/create-eng-auction.mdx
  docs/nil/cookbook/index.mdx
  docs/nil/cookbook/swap/create-swap-contract.mdx
  docs/nil/core-concepts/transaction-lifecycle.mdx
  docs/nil/fundamentals.mdx
  docs/nil/nil-101.mdx
  docs/nil/nild.mdx
  docs/nil/prerequisites.mdx
Labels: documentation

#334 [docs] added Hardhat info to docs
  create-nil-hardhat-project/.env
  create-nil-hardhat-project/README.MD
  create-nil-hardhat-project/hardhat.config.ts
  create-nil-hardhat-project/tasks/deploy-incrementer.ts
  docs/nil/hardhat/getting-started.mdx
  docs/nil/intro.mdx
  docs/sidebar-nil.js
Labels: documentation

#339 Fix integer out of range error on smart account topup in Playground
  explorer_frontend/src/features/account-connector/init.ts
Labels: playground

#340 set wallet input if endpoint exists
  explorer_frontend/src/features/account-connector/components/EndpointScreen.tsx
Labels: playground

#336 Show warnings on solidity compilation in playground
  explorer_frontend/src/features/account-connector/init.ts
  explorer_frontend/src/features/code/init.ts
  explorer_frontend/src/features/code/model.ts
  explorer_frontend/src/features/contracts/init.ts
  explorer_frontend/src/features/logs/init.tsx
Labels: playground

#331 Rename endpoint to rpcUrl in the code
  explorer_frontend/src/features/account-connector/ActiveComponent.ts
  explorer_frontend/src/features/account-connector/components/AccountContainer.tsx
  explorer_frontend/src/features/account-connector/components/MainScreen.tsx
  explorer_frontend/src/features/account-connector/components/RpcUrlScreen.tsx
  explorer_frontend/src/features/account-connector/init.ts
  explorer_frontend/src/features/account-connector/model.ts
  explorer_frontend/src/features/account-connector/validation.ts
  explorer_frontend/src/features/cometa/init.ts
  explorer_frontend/src/features/cometa/model.ts
  explorer_frontend/src/features/contracts/init.ts
  explorer_frontend/src/features/contracts/models/base.ts
  explorer_frontend/src/features/healthcheck/init.ts
  explorer_frontend/src/features/healthcheck/model.ts
  explorer_frontend/src/features/tokens/init.ts
Labels: playground

#348 Fix find and replace dialog in playground
  explorer_frontend/src/features/code/Code.tsx
Labels: playground

#347 Add duplication of deployment errors to deploy modal
  explorer_frontend/src/features/code/Code.tsx
  explorer_frontend/src/features/contracts/components/Deploy/DeployTab.tsx
  explorer_frontend/src/features/contracts/init.ts
  explorer_frontend/src/features/contracts/models/base.ts
Labels: playground

#383 Fix playground deploy button position in modal
  explorer_frontend/src/features/contracts/components/Deploy/DeployContractModal.tsx
  explorer_frontend/src/features/contracts/components/Deploy/DeployTab.tsx
Labels: playground

#327 Wallet Extension: token management
  wallet-extension/package.json
  wallet-extension/public/icons/add-one.svg
  wallet-extension/public/icons/reduce-one.svg
  wallet-extension/public/icons/token/btc.svg
  wallet-extension/public/icons/token/custom.svg
  wallet-extension/public/icons/token/ethereum.svg
  wallet-extension/public/icons/token/nil.svg
  wallet-extension/public/icons/token/usdc.svg
  wallet-extension/public/icons/token/usdt.svg
  wallet-extension/public/locales/en/translation.json
  wallet-extension/src/background/storage/tokens.ts
  wallet-extension/src/features/blockchain/balance.ts
  wallet-extension/src/features/blockchain/faucet.ts
  wallet-extension/src/features/blockchain/index.ts
  wallet-extension/src/features/blockchain/smartAccount.ts
  wallet-extension/src/features/components/wallet/home/ResourceTabs.tsx
  wallet-extension/src/features/components/wallet/home/TokenTab.tsx
  wallet-extension/src/features/store/model.ts
  wallet-extension/src/features/store/model/balance.ts
  wallet-extension/src/features/store/model/token.ts
  wallet-extension/src/features/utils/currency.ts
  wallet-extension/src/features/utils/index.ts
  wallet-extension/src/features/utils/send.ts
  wallet-extension/src/features/utils/token.ts
  wallet-extension/src/features/utils/topUp.ts
  wallet-extension/src/pages/get-started/Loading.tsx
  wallet-extension/src/pages/wallet/AddCustomToken.tsx
  wallet-extension/src/pages/wallet/Home.tsx
  wallet-extension/src/pages/wallet/ManageTokens.tsx
  wallet-extension/src/pages/wallet/Send.tsx
  wallet-extension/src/pages/wallet/TopUp.tsx
  wallet-extension/src/popup.tsx
  wallet-extension/src/router/Wallet.tsx
  wallet-extension/src/router/routes.ts
  wallet-extension/test/integration/faucet.test.ts
  wallet-extension/test/integration/smartAccount.test.ts
Labels: wallet extension

#390 Fix playground deploy button scroll behavior
  explorer_frontend/src/features/contracts/components/Deploy/DeployTab.tsx
  explorer_frontend/src/features/contracts/components/Deploy/ShardIdInput.tsx
  explorer_frontend/src/features/contracts/init.ts
  explorer_frontend/src/features/shared/components/Token/index.tsx
Labels: playground

#393 Fix explorer backend startup sql issue
  explorer_backend/services/tutorials_db.ts
  nix/nilexplorer.nix
Labels: explorer

#394 Temporary disable tutorials explorer backend generation
  explorer_backend/start.ts
Labels: explorer

#333 Niljs faucet allow topup in Number and change client transport prop to readonly
  niljs/src/clients/BaseClient.ts
Labels: niljs

#399 Fixed a bug in Handling External Transactions example contract
  explorer_frontend/src/features/code/assets/HandlingExtTxExample.sol
  explorer_frontend/src/features/contracts/init.ts
Labels: playground

#408 Fix conversion of amount during top-up
  explorer_frontend/src/features/account-connector/init.ts
Labels: playground

#402 Use eth_getShardIdList to get shards amount in playground
  .gitignore
  README.md
  explorer_frontend/src/features/contracts/components/Deploy/ShardIdInput.tsx
  explorer_frontend/src/features/contracts/init.ts
  explorer_frontend/src/features/contracts/models/shardsAmount.ts
  explorer_frontend/src/features/shards/models/model.ts
  nil/client/client.go
  nil/client/direct_client.go
  nil/client/rpc/client.go
  nil/services/rpc/jsonrpc/doc.go
  nil/services/rpc/jsonrpc/eth_api.go
  nil/services/rpc/jsonrpc/eth_shards.go
  nil/services/rpc/rawapi/api.go
  nil/services/rpc/rawapi/client.go
  nil/services/rpc/rawapi/local_system.go
  nil/services/rpc/rawapi/node.go
  nil/services/rpc/rawapi/server.go
  nil/tests/basic/basic_test.go
  niljs/src/clients/PublicClient.test.ts
  niljs/src/clients/PublicClient.ts
Labels: playground, niljs

#416 Fix multiple inputs in playground sc management
  explorer_frontend/src/features/code/init.ts
  explorer_frontend/src/features/contracts/components/Management/MethodInput.tsx
Labels: playground

#366 Fix fetching tx details in playground logs
  explorer_frontend/src/features/logs/components/TxDetails.tsx
  explorer_frontend/src/features/logs/hooks/useRepeatedGetTxByHash.ts
Labels: playground
